name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check_format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Check format
        run: mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
          && sh ./tools/check_format.sh

  test_jraft_core:
    needs: check_format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Maven Test
        run: mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
          && (mvn --projects jraft-core test
            || mvn --projects jraft-core test
            || mvn --projects jraft-core test)

  test_rheakv_core:
    needs: check_format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Maven Test
        run: mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
          && (mvn --projects jraft-rheakv/rheakv-core test
            || mvn --projects jraft-rheakv/rheakv-core test
            || mvn --projects jraft-rheakv/rheakv-core test)

  test_rheakv_pd:
    needs: check_format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Maven Test
        run: mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
          && (mvn --projects jraft-rheakv/rheakv-pd test
            || mvn --projects jraft-rheakv/rheakv-pd test
            || mvn --projects jraft-rheakv/rheakv-pd test)

  test_rpc_grpc_impl:
    needs: check_format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Maven Test
        run: mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
          && (mvn --projects jraft-extension/rpc-grpc-impl test
            || mvn --projects jraft-extension/rpc-grpc-impl test
            || mvn --projects jraft-extension/rpc-grpc-impl test)
